### ISSUE TITLE
Inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [m0rphism/haskell-dmenu#1]
I noticed your recent package upload to Hackage as it was flagged by the matrix buildbot due to  packaging meta-data issues: The build-dependencies have inaccurate versions bounds. Please be aware that accurate version bounds are mandated by the [PVP](http://pvp.haskell.org/), and adherence to the PVP is expected as part of the Hackage guidelines.  This has various knock off consequences, such as Hackage possibly not being able to generate Haddock documentation for your package, as well generally resulting in a poor experience for users since they can run into such compilation errors as well. Specifically, I've noticed the following compile error with GHC 7.8 / base-4.7:

```
[3 of 4] Compiling DMenu.Run        ( src/DMenu/Run.hs, /tmp/matrix-worker/1479592721/dist-newstyle/build/x86_64-linux/ghc-7.8.4/dmenu-0.1.0.1/build/DMenu/Run.o )

src/DMenu/Run.hs:47:42:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<.>’ (imported from Control.Lens),
      ‘<&>’ (imported from Control.Lens)

src/DMenu/Run.hs:61:30:
    Not in scope: ‘readCreateProcessWithExitCode’
    Perhaps you meant ‘readProcessWithExitCode’ (imported from System.Process)

src/DMenu/Run.hs:64:5:
    Not in scope: ‘pure’
    Perhaps you meant ‘pre’ (imported from Control.Lens)

src/DMenu/Run.hs:104:52:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<.>’ (imported from Control.Lens),
      ‘<&>’ (imported from Control.Lens)

src/DMenu/Run.hs:148:39:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<.>’ (imported from Control.Lens),
      ‘<&>’ (imported from Control.Lens)

src/DMenu/Run.hs:150:30:
    Not in scope: ‘readCreateProcessWithExitCode’
    Perhaps you meant ‘readProcessWithExitCode’ (imported from System.Process)

src/DMenu/Run.hs:153:5:
    Not in scope: ‘pure’
    Perhaps you meant ‘pre’ (imported from Control.Lens)

src/DMenu/Run.hs:184:59:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<.>’ (imported from Control.Lens),
      ‘<&>’ (imported from Control.Lens)

src/DMenu/Run.hs:213:9:
    Not in scope: ‘<$>’
    Perhaps you meant one of these:
      ‘<.>’ (imported from Control.Lens),
      ‘<&>’ (imported from Control.Lens)

src/DMenu/Run.hs:213:61:
    Not in scope: ‘pure’
    Perhaps you meant ‘pre’ (imported from Control.Lens)
```

**Comment by m0rphism** [comment]
Thanks for the info! I've updated the cabal file; hope everything works now. Sorry for the silent close before; I thought at first the message was auto-generated by a build bot ;)

**Comment by hvr** [comment]
> I thought at first the message was auto-generated by a build bot ;)

...I'm working on automating that... but it's still a long way... it's surprisingly hard to avoid false positives (which would annoy everyone) without supervising the buildbot's results  :-)
